"""Package to describe kernels.

Description is seen as two different tasks here:
* Take a description (aka. representation) of a kernel in one form and transform it into another. E.g., take
  the AST of a kernel and transform it into a gpflow kernel or a string.
* Take a special, simplified kernel AST and describe it using natural language.

This package provides both abilities.

Example
-------
1) Transforming form AST to gpflow kernel:
```
    > from kerndisc.description import ast_to_kernel
    > kernel = ast_to_kernel(ast)
```
for any valid AST. A valid AST can be generated by using `kernel_to_ast` on ANY gpflow kernel.

2) TODO: Add natural language description example once done.

"""
from ._transform import ast_to_kernel, ast_to_text, kernel_to_ast
from ._util import pretty_ast


__all__ = [
    'ast_to_text',
    'ast_to_kernel',
    'kernel_to_ast',
    'pretty_ast',
]
